Repository DiamondLightSource/workflows, pull requests merged in 2024-07, with the labels that each got.

#49 Disable kyverno background scans
  charts/sessionspaces/Chart.yaml
  charts/sessionspaces/templates/pod-clusterpolicy.yaml
  charts/workflows/Chart.yaml
  charts/workflows/templates/argo-workflow-clusterpolicy.yaml
  charts/workflows/templates/visit-member-clusterpolicy.yaml
Labels: bug, helm

#50 Touch `main.rs` after full copy in sessionspaces Dockerfile
  sessionspaces/Dockerfile
Labels: bug, rust, docker

#52 Fix data directory in `sessionspaces`
  sessionspaces/src/resources/config_maps.rs
Labels: bug, rust

#51 Clean sessionspace logs
  sessionspaces/src/instruments.rs
  sessionspaces/src/main.rs
  sessionspaces/src/permissionables/mod.rs
Labels: rust

#58 Improve error reporting whilst updating sessionspaces
  sessionspaces/src/main.rs
Labels: enhancement, rust

#61 Create dependabot cargo update group for `kube` & `k8s-openapi`
  .github/dependabot.yaml
Labels: dependencies, github actions

#65 Fix `sessionspaces` chart request rate env var
  charts/sessionspaces/Chart.yaml
  charts/sessionspaces/templates/deployment.yaml
Labels: bug, helm

#68 Fix `sessionspaces` ldap domain name
  charts/sessionspaces/Chart.yaml
  charts/sessionspaces/values.yaml
Labels: bug, helm

#69 Update `sessionspaces` chart `appVersion`
  charts/sessionspaces/Chart.yaml
Labels: helm

#67 Disable argo-events app
  charts/argocd-apps/Chart.yaml
  charts/argocd-apps/values.yaml
Labels: helm

#70 Update sealed secrets for new vCluster database deployment
  charts/sessionspaces/Chart.yaml
  charts/sessionspaces/templates/ispyb-secret.yaml
  charts/workflows/Chart.yaml
  charts/workflows/templates/argo-server-sso-secret.yaml
Labels: helm

#72 Deploy app of apps for cluster bootstrapping
  README.md
  charts/verflixt/Chart.yaml
  charts/verflixt/templates/vxt.yaml
  charts/verflixt/values.yaml
  charts/workflows-cluster/Chart.yaml
  charts/workflows-cluster/dev-values.yaml
  charts/workflows-cluster/values.yaml
Labels: bug, helm

#74 Increase timeout duration for CustomResourceDefinitions in kyverno CI
  .github/workflows/kyverno-policy.yaml
Labels: helm, github actions

#75 Template target revision in app of apps
  charts/argocd-apps/Chart.yaml
  charts/argocd-apps/templates/events-application.yaml
  charts/argocd-apps/templates/kyverno-application.yaml
  charts/argocd-apps/templates/sealed-secrets-application.yaml
  charts/argocd-apps/templates/sessionspaces-application.yaml
  charts/argocd-apps/templates/workflows-application.yaml
  charts/argocd-apps/values.yaml
Labels: enhancement, helm

#77 Increase kyverno resource requests & limits
  charts/argocd-apps/Chart.yaml
  charts/argocd-apps/values.yaml
Labels: bug, helm

#78 Increase vcluster memory requests & limits
  charts/workflows-cluster/Chart.yaml
  charts/workflows-cluster/values.yaml
Labels: bug, helm

#81 Set kyverno app to a fixed target revision
  charts/argocd-apps/Chart.yaml
  charts/argocd-apps/values.yaml
Labels: bug, helm

#80 Move `sessionspaces` chainsaw tests to `sessionsapces` chart
  charts/sessionspaces/Chart.yaml
  charts/sessionspaces/test-policy/pod-hostpath/chainsaw-test.yaml
  charts/sessionspaces/test-policy/pod-securitycontext/chainsaw-test.yaml
Labels: helm

#86 Specify resources for vcluster coredns
  charts/workflows-cluster/Chart.yaml
  charts/workflows-cluster/values.yaml
Labels: helm

#87 Checkout docs with LFS
  .github/workflows/docs.yaml
Labels: documentation

#88 Do LFS pull on build not lint
  .github/workflows/docs.yaml
Labels: documentation

#92 Lookup existing argo workflows postgres secret before generating anew
  charts/workflows/Chart.yaml
  charts/workflows/templates/_helpers.tpl
  charts/workflows/templates/pgpool-passwords-secret.yaml
  charts/workflows/templates/postgres-application-passwords-secret.yaml
  charts/workflows/templates/postgres-initdb-script-secret.yaml
  charts/workflows/templates/postgres-passwords-secret.yaml
Labels: bug, helm

#83 Extend `sessionspaces` pod policy to mutate ephemeral containers
  charts/sessionspaces/Chart.yaml
  charts/sessionspaces/templates/pod-clusterpolicy.yaml
  charts/sessionspaces/test-policy/pod-securitycontext/chainsaw-test.yaml
Labels: bug, helm

#101 Add mx group and setup repo
  charts/groups/Chart.yaml
  charts/groups/values.yaml
Labels: enhancement, helm

#102 Add documnent separator to groups templates
  charts/groups/Chart.yaml
  charts/groups/templates/applications.yaml
  charts/groups/templates/namespaces.yaml
  charts/groups/templates/projects.yaml
Labels: bug, helm

#103 Add explanation of session namespace provisioning
  docs/explanations/session_namespces.md
Labels: documentation
