Repository DiamondLightSource/workflows, pull requests merged in 2024-12, with the labels that each got.

#315 Bump `argo-workflows` to resolve UI submission issues
  charts/workflows/Chart.lock
  charts/workflows/Chart.yaml
Labels: bug, dependencies, helm

#316 Use correct upstream url for `graph-proxy`
  charts/graph-proxy/Chart.yaml
  charts/graph-proxy/values.yaml
Labels: bug, helm

#317 Use `https` for `graph-proxy` upstream connection
  charts/graph-proxy/Chart.yaml
  charts/graph-proxy/values.yaml
Labels: bug, helm

#318 Update README.md
  README.md
Labels: documentation

#326 fix(dependabot): add conventional commit prefix to dependabot
  .github/dependabot.yaml
Labels: github actions

#325 fix: Bump graph proxy rust version from 1.80.1 to 1.83.0
  graph-proxy/.devcontainer/Dockerfile
  graph-proxy/Dockerfile
Labels: rust
