Repository DiamondLightSource/workflows, pull requests merged in 2024-09, with the labels that each got.

#169 Ignore secret differences
  charts/argocd-apps/Chart.yaml
  charts/argocd-apps/templates/workflows-application.yaml
Labels: bug, helm

#170 add exports for workflow-lib components and types
  frontend/workflows-lib/lib/main.ts
Labels: Frontend, TypeScript

#171 refactor fake data in workflows-lib stories
  frontend/workflows-lib/stories/TasksDynamic.stories.tsx
  frontend/workflows-lib/stories/TasksFlow.stories.tsx
  frontend/workflows-lib/stories/TasksTable.stories.tsx
  frontend/workflows-lib/stories/WorkflowAccordion.stories.tsx
  frontend/workflows-lib/stories/WorkflowStack.stories.tsx
  frontend/workflows-lib/stories/common.ts
Labels: Frontend, TypeScript

#178 fix argo workflow API schema
  graph-proxy/argo-workflows-openapi/build.rs
Labels: rust

#183 add tasks to graphql proxy
  graph-proxy/src/graphql/workflows.rs
Labels: enhancement, rust

#187 Bump argo workflows chart to `0.42.3`
  charts/workflows/Chart.lock
  charts/workflows/Chart.yaml
Labels: helm

#189 fix typo in stories faketasks
  frontend/workflows-lib/stories/common.ts
Labels: Frontend

#188 Skip oauth2 proxy redirect for various methods when accessing Argo Server API
  charts/workflows/Chart.yaml
  charts/workflows/values.yaml
Labels: bug, helm

#191 fix frontend bugs
  frontend/workflows-lib/lib/components/common/StatusIcons.tsx
  frontend/workflows-lib/lib/components/workflow/TasksFlowUtils.ts
  frontend/workflows-lib/lib/components/workflow/TasksTable.tsx
  frontend/workflows-lib/lib/types.ts
Labels: Frontend

#194 Add `prefix-path` option to `graph-proxy`
  graph-proxy/src/main.rs
Labels: enhancement, rust
