Repository DiamondLightSource/workflows, pull requests merged in 2024-08, with the labels that each got.

#113 Configure `yaml` and `tpl` files to be detected by linguist as `yaml`
  .gitattributes
Labels: documentation

#114 Improve chainsaw test CI setup
  .github/workflows/kyverno-policy.yaml
Labels: github actions

#105 Create policy to apply podCG to Workflows and Workflow Templates
  .github/workflows/kyverno-policy.yaml
  charts/workflows/Chart.yaml
  charts/workflows/templates/sessionspace-clusterpolicy.yaml
  charts/workflows/test-policy/workflow-pod-gc/chainsaw-test.yaml
Labels: enhancement, helm, github actions

#123 Set up magnetic materials group and repo
  charts/groups/Chart.yaml
  charts/groups/values.yaml
Labels: enhancement, helm

#121 Setup workflows component library
  frontend/.devcontainer/devcontainer.json
  frontend/.gitignore
  frontend/package.json
  frontend/workflows-lib/eslint.config.js
  frontend/workflows-lib/lib/vite-env.d.ts
  frontend/workflows-lib/package.json
  frontend/workflows-lib/tsconfig.app.json
  frontend/workflows-lib/tsconfig.json
  frontend/workflows-lib/tsconfig.node.json
  frontend/workflows-lib/vite.config.ts
  frontend/yarn.lock
Labels: UI, TypeScript

#132 Bump app version to `0.1.0-rc14` in `sessionspaces` chart
  charts/sessionspaces/Chart.yaml
Labels: helm

#133 Remove member refs from `sessionspace` ConfigMaps
  sessionspaces/src/resources/config_map.rs
Labels: rust

#134 Bump app version to 0.1.0-rc15 in `sessionspaces` chart
  charts/sessionspaces/Chart.yaml
Labels: helm

#136 Remove helm chart publishing from CI
  .github/workflows/charts.yaml
Labels: helm, github actions

#137 Fully qualify various `sessionspaces` names & paths
  .github/workflows/sessionspaces-container.yaml
  .gitignore
  sessionspaces/.devcontainer/devcontainer.json
  sessionspaces/.gitignore
Labels: rust, helm, github actions

#143 add CI to deploy storybook to github pages
  .github/workflows/github-pages.yaml
Labels: github actions, Frontend

#144 add links for docs and storybook to README
  README.md
Labels: documentation

#145 Skip oauth2 proxy for /assets
  charts/workflows/Chart.yaml
  charts/workflows/values.yaml
Labels: enhancement, helm

#147 Skip oauth2 proxy for `/assets`
  charts/workflows/Chart.yaml
  charts/workflows/values.yaml
Labels: bug, helm

#148 Disable argo workflows UI modals
  charts/workflows/Chart.yaml
  charts/workflows/values.yaml
Labels: enhancement, helm

#159 Group rust opentelemety dependabot updates
  .github/dependabot.yaml
Labels: dependencies, github actions
