Repository DiamondLightSource/workflows, pull requests merged in 2024-06, with the labels that each got.

#19 Add ClusterRole Templates for Visit Member and Argo Workflows
  charts/workflows/Chart.yaml
  charts/workflows/templates/clusterrole-argo-workflows.yaml
  charts/workflows/templates/clusterrole-visit-member.yaml
Labels: enhancement, helm

#21 Fix `Sessionspaces` `clippy` warnings
  sessionspaces/src/main.rs
  sessionspaces/src/permissionables/posix_attributes.rs
  sessionspaces/src/permissionables/session.rs
  sessionspaces/src/resources/config_maps.rs
  sessionspaces/src/resources/namespace.rs
Labels: rust

#22 Add `managed-by` label to sessionspaces resources
  sessionspaces/src/resources/config_maps.rs
  sessionspaces/src/resources/mod.rs
  sessionspaces/src/resources/namespace.rs
Labels: enhancement, rust

#26 Add filesystem mounting how-to guide
  docs/how-tos/mount-filesystem.md
Labels: documentation

#31 Setup dependabot
  .github/dependabot.yaml
Labels: github actions

#34 Increase timeout for clusterpolicy in github policy job
  .github/workflows/kyverno-policy.yaml
Labels: enhancement

#43 Fix insecure helm urls
  .github/workflows/charts.yaml
  .github/workflows/kyverno-policy.yaml
  charts/workflows/Chart.lock
  charts/workflows/Chart.yaml
Labels: helm
