Repository DiamondLightSource/workflows, pull requests merged in 2024-05, with the labels that each got.

#5 Add chart dependencies to ct linting CI
  .github/workflows/charts.yaml
Labels: bug, helm, github actions

#9 Remove namespace manifest from vcluster deployment
  README.md
  charts/workflows-cluster/Chart.yaml
  charts/workflows-cluster/values.yaml
Labels: helm

#12 Deploy only external charts in dev cluster
  charts/workflows-cluster/Chart.yaml
  charts/workflows-cluster/dev-values.yaml
Labels: helm

#15 Patch to fix manual deployment of argo-events in workflow namespace
  README.md
  charts/events/Chart.yaml
  charts/events/templates/event-bus.yaml
  charts/events/templates/event-sources.yaml
  charts/events/values.yaml
Labels: bug, helm

#16 Move argo workflows server ingress to workflows chart
  charts/workflows-cluster/Chart.yaml
  charts/workflows-cluster/dev-values.yaml
  charts/workflows-cluster/values.yaml
  charts/workflows/Chart.yaml
  charts/workflows/dev-values.yaml
  charts/workflows/templates/argo-server-ingress.yaml
  charts/workflows/values.yaml
Labels: helm
