Repository DiamondLightSource/workflows, pull requests merged in 2024-11, with the labels that each got.

#249 Allow any header in CORS requests
  graph-proxy/src/main.rs
Labels: bug, rust

#251 Fix `graph-proxy` failure cascade when parsing workflow templates
  graph-proxy/Cargo.toml
  graph-proxy/src/graphql/workflow_templates.rs
Labels: bug, rust

#250 Tidy `sessionspaces` chart
  .github/workflows/_kyverno_policy.yaml
  charts/sessionspaces/.gitignore
  charts/sessionspaces/Chart.lock
  charts/sessionspaces/Chart.yaml
  charts/sessionspaces/templates/_helpers.tpl
  charts/sessionspaces/templates/clusterrole.yaml
  charts/sessionspaces/templates/clusterrolebinding.yaml
  charts/sessionspaces/templates/deployment.yaml
  charts/sessionspaces/templates/ispyb-secret.yaml
  charts/sessionspaces/templates/pod-clusterpolicy.yaml
  charts/sessionspaces/templates/serviceaccount.yaml
  charts/sessionspaces/values.yaml
Labels: helm

#256 Setup `dependabot` for `frontend`
  .github/dependabot.yaml
Labels: dependencies, github actions, javascript

#265 Tidy up `graph-proxy` chart
  charts/graph-proxy/Chart.yaml
  charts/graph-proxy/templates/deployment.yaml
  charts/graph-proxy/templates/ingress.yaml
  charts/graph-proxy/templates/service.yaml
  charts/graph-proxy/templates/serviceaccount.yaml
Labels: helm

#280 Use workspace for `graph-proxy` sub-crates
  graph-proxy/Cargo.toml
  graph-proxy/argo-workflows-openapi/Cargo.lock
  graph-proxy/argo-workflows-openapi/Cargo.toml
  graph-proxy/argo-workflows-openapi/src/lib.rs
Labels: rust

#270 Add router to dashboard
  frontend/.devcontainer/devcontainer.json
  frontend/dashboard/package.json
  frontend/dashboard/src/errorpage.tsx
  frontend/dashboard/src/main.tsx
  frontend/dashboard/src/routes/workflows.tsx
  frontend/yarn.lock
Labels: Frontend, TypeScript

#283 Update `vcluster` to `v0.20.5`
  charts/workflows-cluster/Chart.lock
  charts/workflows-cluster/Chart.yaml
Labels: dependencies, helm

#285 Fix `sessionspaces` ispyb secret reference
  charts/sessionspaces/Chart.yaml
  charts/sessionspaces/templates/deployment.yaml
  charts/sessionspaces/values.yaml
Labels: bug, helm

#284 Bump `workflows` chart `postgres-ha` dependency to `14.3.9`
  charts/workflows/Chart.lock
  charts/workflows/Chart.yaml
Labels: dependencies, helm

#286 Expose `argo-workflows` server at `argo-workflows.workflows.diamond.ac.uk`
  charts/workflows/Chart.yaml
  charts/workflows/templates/ingress-tls-secret.yaml
  charts/workflows/values.yaml
Labels: enhancement, helm

#289 Build dashboard with nginx container
  .github/workflows/_dashboard_container.yaml
  .github/workflows/ci.yaml
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/container_utils/default.conf.template
  frontend/dashboard/relay.config.json
Labels: enhancement, github actions, docker

#297 Bump charts to latest app version
  charts/dashboard/Chart.yaml
  charts/graph-proxy/Chart.yaml
  charts/sessionspaces/Chart.yaml
Labels: helm

#287 Expose `argo-cd` at `argo-cd.workflows.diamond.ac.uk`
  charts/argocd/Chart.lock
  charts/argocd/Chart.yaml
  charts/argocd/templates/ingress-tls-secret.yaml
  charts/argocd/templates/ingress.yaml
  charts/argocd/values.yaml
Labels: enhancement, helm

#300 Bump `argo-workflows` chart version to `0.45.0`
  charts/workflows/Chart.lock
  charts/workflows/Chart.yaml
Labels: helm

#302 Fix dashboard CORS error by using correctly configured client
  frontend/dashboard/.env.production
Labels: bug, Frontend

#301 Bump `oauth2-proxy` version in workflows to `7.8.0`
  charts/workflows/Chart.lock
  charts/workflows/Chart.yaml
Labels: dependencies, helm

#304 Bump app versions to `0.1.0-rc25`
  charts/dashboard/Chart.yaml
  charts/graph-proxy/Chart.yaml
  charts/sessionspaces/Chart.yaml
Labels: helm

#303 add info logs to graph-proxy main
  graph-proxy/src/main.rs
Labels: rust

#305 Fix `graph-proxy` docker image caching
  graph-proxy/Dockerfile
Labels: bug, rust, docker
