Repository DiamondLightSource/workflows, pull requests merged in 2025-04, with the labels that each got.

#517 feat(workflows): delete own workflows
  charts/workflows/Chart.yaml
  charts/workflows/templates/visit-member-clusterrole.yaml
Labels: helm

#521 fix(graph-proxy): removed overly-descriptive name for template_ref
  backend/graph-proxy/src/graphql/workflows.rs
Labels: rust

#519 Filter creator
  backend/graph-proxy/src/graphql/workflows.rs
Labels: rust

#525 configure tracing and ingress for telemetry
  charts/monitoring/Chart.yaml
  charts/monitoring/values.yaml
Labels: enhancement, helm

#520 Graph parameters
  backend/graph-proxy/src/graphql/workflows.rs
Labels: enhancement, rust

#540 feat(dashboard): add ui component tests
  frontend/workflows-lib/lib/components/common/StatusIcons.tsx
  frontend/workflows-lib/lib/components/workflow/ImageGallery.tsx
  frontend/workflows-lib/lib/components/workflow/TasksFlowNode.tsx
  frontend/workflows-lib/package.json
  frontend/workflows-lib/tests/components/ArtifactFilteredList.test.tsx
  frontend/workflows-lib/tests/components/ImageGallery.test.tsx
  frontend/workflows-lib/tests/components/StatusIcons.test.tsx
  frontend/workflows-lib/tests/components/TaskInfo.test.tsx
  frontend/workflows-lib/tests/components/TasksFlowNode.test.tsx
  frontend/workflows-lib/tests/components/WorkflowsErrorBoundary.test.tsx
  frontend/workflows-lib/tests/components/WorkflowsNavbar.test.tsx
  frontend/workflows-lib/tests/components/data.ts
Labels: enhancement, typescript

#542 fix(ci): remove bootstrap-sha and last-release-sha from release please
  release-please-config.json
Labels: github actions
